### ISSUE TITLE
Improvement 

### ISSUE THREAD

**Issue by DubStepMad** [sherwinchia/livewire-image-uploader#1]
Would be nice if you could tie this into spatie media library as an option

https://spatie.be/docs/laravel-medialibrary/v9/introduction

**Comment by sherwinchia** [comment]
Hi @DubStepMad , thank you for your suggestion. I'll look into it later when I'm free.

**Comment by sherwinchia** [comment]
thank you for your suggestion. I'll look into it later when I'm free.
